name: okr_os
description: OKR Application using Flutter and Firebase
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.7.1
  dio: ^5.4.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  flutter_modular: ^5.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
