name: okr_os
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.1.1
  mobx: ^2.3.0

  google_sign_in: ^6.1.4
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  http: ^0.13.6
  intl: ^0.18.1

  flare_flutter: ^3.0.2
  animations: ^2.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
